### ISSUE TITLE
[FE] Make the login process

### ISSUE THREAD

**Issue by jordimorillo** [IT-Academy-BCN/ita-profiles#186]
As a visitor with credentials
I want to do login and see my student resume.

To do this, I will:
- open the frontend
- click the upper right button to login
- enter my DNI and my password (that you can find in the swagger endpoint attached below) 
- and then I shall see my resume view (or something else if it is not still advanced enough to be shown) that indicates that I am logged into my account

I will know this is accomplished when I can follow these steps successfully from the main branch of the project.

⚠️ REMEMBER ⚠️
After successfully logging in, the backend endpoint will hand us a TOKEN that frontend must store as a session token that will be attached in any query or command inside the user profile/resume.

---
### Tasks

- [x] modify text on buttons in 'Acceso restringido' screen to simplify navigation
- [x] modify login screen to match figma
- [x] post login data to backend
- [x] on successful login change context state to 'logged in'
- [x] on successful login navigate to profile page
- [x] on failed login attempt display error message
- [x] Add testing

### Extra tasks (if there's time)

- [x] make logo to navigate home on click
- [x] on successful login change navbar 'login/register' icon to profile icon

---

swagger login endpoint:
http://localhost:8000/api/documentation#/SignInUser/signin

![Image](https://github.com/IT-Academy-BCN/ita-profiles/assets/11392091/e0599d65-0db1-41b3-80e3-6f71bdfc041e)
